### ISSUE TITLE
Output names need sanitization

### ISSUE THREAD

**Issue by TrueCyberAxe** [erikelisath/keep-to-markdown#4]
Get the error when it tries to convert, which to me indicates the colons need sanitized out

Traceback (most recent call last):
  File "C:\Users\redacted\Desktop\takeout-20210501T112904Z-001\keep-to-markdown.py", line 137, in <module>
    read_write_notes(sys.argv[1])
  File "C:\Users\redacted\Desktop\takeout-20210501T112904Z-001\keep-to-markdown.py", line 88, in read_write_notes
    with open(f'notes/{title}.md', 'w') as mdfile:
OSError: [Errno 22] Invalid argument: 'notes/2021-05-01 12:52:19 edited.md'

**Comment by erikelisath** [comment]
Thanks for reporting the error!

What is the OS? Windows 10? 

I think that the the hardcoded slash in `open(f'notes/{title}.md', 'w')` will fail in Windows. 
Will look for a Windows version, because at this moment its only working on linux/mac.

**Comment by erikelisath** [comment]
![ktm_error_on_windows](https://user-images.githubusercontent.com/15351619/116790127-0a15c980-aab3-11eb-9d72-825ea5cb2d9c.jpg)
definitly a Windows issue - tested on Windows 7 with python 3.8

**Comment by erikelisath** [comment]
Fixed the Windows issues with #6. 
If there still issues, please reopen the ticket.

**Comment by TrueCyberAxe** [comment]
Hard coded / works fine in windows, windows has had support for / since xp, hence how you can keep paths safe across POSIX and Windows Systems

It will only fail if the notes folder doesnt exist, but that's easy to account for.

It was python 3.9.4 and Windows 10 i was using.

**Comment by TrueCyberAxe** [comment]
I also noticed you are doing title = clean_title(str(data['title']))

that will cause you to write the "cleaned" and not original title on line 108 hence why i used a different variable in my commit

**Comment by erikelisath** [comment]
Yes thats right, Windows can deal the hardcoded version of `/`, but its not good to hardcoding this. Removing it will reduce possible bugs. 

Cleaning the title in your way or mine, is the same. But you have drawn my attention to it, to remove illegal chars for the title. Adjusted it for the particular OS, since Windows has more characters that should not be used as a filename. Also I changed the timestamp to reduce the number of iterations to remove chars. On Linux there was no issue to use the timestamp with special chars but it doesn't work on Windows well.

Thanks for helping to make the code better!

**Comment by TrueCyberAxe** [comment]
I meant with your update you are not writing the original title inside the file anymore (line 108) you've changed both the filename and the text you're writing inside the note itself, surley the intention is to have the original un cleaned title should be written inside and the cleaned and truncated title as the filename.

No problem.

**Comment by erikelisath** [comment]
Oh I see. I was focused on the filename issue that I forget the title inside the file themself. Im sorry I will fix that!

**Comment by erikelisath** [comment]
Should be correct now with #7. Will wait for you feedback before merging. I think that the uncleaned title will be fine for the inside title. Or Google is to tolerant with note title.

**Comment by erikelisath** [comment]
Thanks for your support! Now the code is working better on Windows.
